#ifndef __WCLASSES_FORWARD_DECLARE_H
#define __WCLASSES_FORWARD_DECLARE_H
#include "WstringBase_class.h"
#include <wondermacros/objects/x/forward_declare.h>
#include "WstringChunk_class.h"
#include <wondermacros/objects/x/forward_declare.h>
#include "WstringRope_class.h"
#include <wondermacros/objects/x/forward_declare.h>
#include "Wstring_class.h"
#include <wondermacros/objects/x/forward_declare.h>
#include "Wwriter_class.h"
#include <wondermacros/objects/x/forward_declare.h>
#include "WwriterMemory_class.h"
#include <wondermacros/objects/x/forward_declare.h>
#include "Wreader_class.h"
#include <wondermacros/objects/x/forward_declare.h>
#include "WreaderMemory_class.h"
#include <wondermacros/objects/x/forward_declare.h>
#include "Wbind_class.h"
#include <wondermacros/objects/x/forward_declare.h>
#include "WbindV_class.h"
#include <wondermacros/objects/x/forward_declare.h>
#include "WbindVptr_class.h"
#include <wondermacros/objects/x/forward_declare.h>
#include "WbindI_class.h"
#include <wondermacros/objects/x/forward_declare.h>
#include "WbindD_class.h"
#include <wondermacros/objects/x/forward_declare.h>
#endif
